stages: 
  - deploy

default:
  image: images.paas.redhat.com/business-services-analytics/python:c09-py311-uv
  cache:
    key: cache-$CI_COMMIT_REF_SLUG
    paths:
      - .venv # This is the path of the venv created below
      - /opt/app-root/src/.cache/uv
  tags:
    - shared-podman

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Before Template
.install-deps-template: &install-deps
  before_script:
    - uv sync --locked --no-editable --all-extras

pages:
  <<: *install-deps
  stage: deploy
  script:
    - uv run mkdocs build --verbose -d public
  artifacts:
    paths:
    - public
  only:
    - main